version: "2"
services:
  web:
    container_name: lisence-app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
